function M = function_M(in1)
%function_M
%    M = function_M(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    08-Dec-2022 11:09:17

M = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0],[4,4]);
