function T = jacobian_T(in1)
%jacobian_T
%    T = jacobian_T(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    12-Dec-2022 19:34:02

x5 = in1(5,:);
t2 = sin(x5);
t3 = t2.^2;
t4 = t3.*9.678517074195902e+18;
t5 = t4-2.977836368612714e+19;
t6 = 1.0./t5;
t7 = t2.*t6.*1.463669878895411e+17;
t8 = -t7;
T = reshape([0.0,0.0,0.0,t6.*-1.902770842564035e+18,0.0,t8,0.0,0.0,0.0,t8,0.0,t6.*(t3.*3.739953018957269e+16+1.762033354208707e+17).*(-1.189303307529909e-1)],[6,2]);
