function h = observation_model_h_EKF(in1)
%observation_model_h_EKF
%    H = observation_model_h_EKF(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    12-Dec-2022 19:34:02

v1 = in1(7,:);
v2 = in1(8,:);
v3 = in1(9,:);
v4 = in1(10,:);
x1 = in1(1,:);
x2 = in1(2,:);
x4 = in1(4,:);
x5 = in1(5,:);
h = [v1+x5;v2+x4;v3+x1;v4+sqrt((x1-2.1e+1./5.0).^2+x2.^2)];
